apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc03
  namespace: training03
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

